[package]
name = "rustparticles"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2.83"
lazy_static = "1.4.0"
rand = "0.8.5"
getrandom = { version="0.2.8",  features = ["js"] }

[lib]
crate-type = ["cdylib"]
 
[profile.dev]
opt-level = "s"
